name: '*next*'
verbose: true
package:
  - '@sapphire/async-queue'
  - '@sapphire/decorators'
  - '@sapphire/discord-utilities'
  - '@sapphire/discord.js-utilities'
  - '@sapphire/eslint-config'
  - '@sapphire/event-iterator'
  - '@sapphire/fetch'
  - '@sapphire/phisherman'
  - '@sapphire/prettier-config'
  - '@sapphire/ratelimits'
  - '@sapphire/result'
  - '@sapphire/snowflake'
  - '@sapphire/stopwatch'
  - '@sapphire/string-store'
  - '@sapphire/time-utilities'
  - '@sapphire/ts-config'
  - '@sapphire/utilities'
  - '@sapphire/phisherman'
